openapi: 3.0.1
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Returns "hello"
      operationId: hello
      responses:
        200:
          description: OK
          content:
            application/json:
               schema:
                 type: string